apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: hello-world.local
      http:
        paths:
          - path: /spring
            pathType: Prefix
            backend:
              service:
                name: spring-app-service
                port:
                  number: 8080 # Matches the `port` defined in your service
